// Module: authentication — consolidated Playwright specs (19 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';
import { OrangeHRMPage } from '../../pages/orange-hrm/orange-hrm.page';

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("001 - Verify login page displays all required elements on load", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await expect(page.locator("img[alt='company-branding']")).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Password")).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Login" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Forgot your password?")).toBeVisible({ timeout: 15000 });
});

test.describe('User Login', () => {
  test('002 - Verify successful login with valid credentials redirects to Dashboard', async ({ page }) => {
    const orangeHRM = new OrangeHRMPage(page);

    // 1. Navigate to login page → Login form is displayed with Username and Password fields and a Login button
    // 2. Enter 'Admin' into the Username field → The Username field shows 'Admin'; no validation error appears
    // 3. Enter 'admin123' into the Password field → The Password field shows masked characters; no validation error appears
    // 4. Click the 'Login' button → The user is redirected to the Dashboard page within 3 seconds
    await orangeHRM.login('Admin', 'admin123');

    // 5. Observe the Dashboard header and session cookie → The Dashboard content is displayed and a session cookie is set
    const cookies = await page.context().cookies();
    expect(cookies.length).toBeGreaterThan(0);
  });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("003 - Verify login fails with an incorrect password for a valid username", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await expect(page.getByRole("button", { name: "Login" })).toBeVisible({ timeout: 15000 });
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("WrongPass999");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("004 - Verify identical 'Invalid credentials' message for unknown username and for wrong password", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("NoSuchUser2024");
  await page.getByPlaceholder("Password").fill("WrongPass999");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials", { exact: true })).toContainText("", { timeout: 15000 });
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("");
  await page.getByPlaceholder("Password").fill("WrongPass999");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials", { exact: true })).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials", { exact: true })).toContainText("Invalid credentials", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("005 - Verify 'Required' validation for blank Username, blank Password, and both blank", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true }).nth(0)).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(1)).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/auth/login"), { timeout: 15000 });
  await page.getByPlaceholder("Username").fill("");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true }).nth(0)).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/auth/login"), { timeout: 15000 });
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true }).nth(0)).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("006 - Verify password characters are masked on screen while typing", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Password").fill("admin123");
  await expect(page.locator("input[name=\"password\"][type=\"password\"]")).toBeVisible({ timeout: 15000 });
  await expect(page.locator("input[name=\"password\"][type=\"password\"]")).toBeVisible({ timeout: 15000 });
  await expect(page.locator("input[name=\"password\"][type=\"password\"]")).toBeVisible({ timeout: 15000 });
  await expect(page.locator("input[name=\"password\"][type=\"password\"]")).toBeVisible({ timeout: 15000 });
  await expect(page.locator("input[name=\"password\"][type=\"password\"]")).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("007 - Verify Password is NOT trimmed and surrounding spaces are treated as significant", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill(" admin123 ");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("008 - Verify pressing Enter in the Password field triggers login equivalent to clicking Login", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByPlaceholder("Password").press("Enter");
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("009 - Verify pressing Enter with empty fields triggers the same 'Required' validation as clicking Login", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").click();
  await page.getByPlaceholder("Username").press("Enter");
  await expect(page.getByText("Required", { exact: true }).nth(0)).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(1)).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(0)).toContainText("Required", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(1)).toContainText("Required", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("010 - Verify 'Forgot your password?' link navigates to the Password Reset page", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await expect(page.getByText("Forgot your password?")).toBeVisible({ timeout: 15000 });
  await page.getByText("Forgot your password?").click();
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/requestPasswordResetCode"), { timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Reset Password" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("011 - Verify returning to Login from the Password Reset page shows a clean, empty form", async ({ page }) => {
  await page.goto("/");
  await page.getByText("Forgot your password?").click();
  await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Reset Password" })).toBeVisible({ timeout: 15000 });
  await page.getByRole("button", { name: "Cancel" }).click();
  await expect(page.getByRole("button", { name: "Login" })).toBeVisible({ timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page.locator("input[name=\"password\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toContainText("", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("012 - Verify direct access to a protected page without a session redirects to Login", async ({ page }) => {
  await page.goto("/web/index.php/dashboard/index");
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
  await expect(page.getByRole("button", { name: "Login" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
  await expect(page.locator("h6.oxd-topbar-header-breadcrumb-module")).toBeHidden({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("013 - Verify browser Back after logout does not re-expose an authenticated Dashboard", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await page.locator("span.oxd-userdropdown-tab").click();
  await page.getByText("Logout", { exact: true }).click();
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await page.locator("body").press("Alt+ArrowLeft");
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page.getByRole("button", { name: "Login" })).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Password")).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("014 - Verify session cookie is issued with Secure and HttpOnly flags on login", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("015 - Verify credentials are submitted over HTTPS in the POST body and not in the URL", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
  await page.getByPlaceholder("Username").fill("");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/dashboard/index"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("016 - Verify script injection input in Username is sanitized and does not execute", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("<script>alert('xss')</script>");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("017 - Verify SQL injection attempt in credentials is prevented and does not authenticate", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("' OR '1'='1");
  await page.getByPlaceholder("Password").fill("' OR '1'='1");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("018 - Verify Username boundary lengths of 1 and 100 characters are accepted for validation", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("A");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.locator(".oxd-alert-content-text")).toContainText("Invalid credentials", { timeout: 15000 });
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
  await page.getByPlaceholder("Password").fill("");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.locator(".oxd-alert-content-text")).toContainText("Invalid credentials", { timeout: 15000 });
});

test.describe('Field Validation', () => {
  test('019 - Verify leading and trailing spaces in Username are trimmed before validation', async ({ page }) => {
    const orangeHRM = new OrangeHRMPage(page);

    // 1. Navigate to the login page → Login form is displayed
    // 2. Enter '  Admin  ' (with two leading and two trailing spaces) into the Username field → The padded value is accepted into the field
    // 3. Enter 'admin123' into the Password field → The Password field shows masked characters
    // 4. Click the 'Login' button → The trimmed username 'Admin' is used for validation and the user is redirected to the Dashboard
    await orangeHRM.login('  Admin  ', 'admin123');

    // Post-login landmark: user reached the Dashboard
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 30000 });
  });
});
